name: å‘å¸ƒé¢„è§ˆç‰ˆ

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  contents: write

jobs:
  beta-info:
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'release-please')"
    outputs:
      short_commit_hash: ${{ steps.get-sha.outputs.SHORT_COMMIT_HASH }}
      build_timestamp: ${{ steps.get-build-timestamp.outputs.BUILD_TIMESTAMP }}

    steps:
      - name: æ£€å‡ºä»£ç 
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: è·å–åˆ†æ”¯çš„æœ€æ–°æäº¤å“ˆå¸Œ
        id: get-sha
        run: |
          branch=${{ github.event.pull_request.head.ref || github.ref_name }}
          git fetch --depth=1 origin $branch
          SHORT_COMMIT_HASH=$(git rev-parse --short FETCH_HEAD)
          echo "SHORT_COMMIT_HASH=$SHORT_COMMIT_HASH" >> $GITHUB_ENV
          echo "SHORT_COMMIT_HASH=$SHORT_COMMIT_HASH" >> $GITHUB_OUTPUT
          echo "åˆ†æ”¯ $branch çš„æœ€æ–°çŸ­å“ˆå¸Œä¸º: $SHORT_COMMIT_HASH"

      - name: è·å–æ„å»ºæ—¶é—´
        id: get-build-timestamp
        run: |
          branch=${{ github.event.pull_request.head.ref || github.ref_name }}
          git fetch origin $branch --depth=1
          BUILD_TIMESTAMP_UTC=$(git show -s --format=%cd --date=iso-strict origin/$branch)
          echo "BUILD_TIMESTAMP_UTC=$BUILD_TIMESTAMP_UTC"
          BUILD_TIMESTAMP=$(TZ=Asia/Shanghai date -d "$BUILD_TIMESTAMP_UTC" +"%Y-%m-%d %H:%M:%S")

          echo "BUILD_TIMESTAMP=$BUILD_TIMESTAMP" >> $GITHUB_ENV
          echo "BUILD_TIMESTAMP=$BUILD_TIMESTAMP" >> $GITHUB_OUTPUT
          echo "æ„å»ºæ—¶é—´: $BUILD_TIMESTAMP"

  build:
    if: "!startsWith(github.head_ref, 'release-please')"
    uses: ./.github/workflows/build.yaml

  create-release:
    if: "!startsWith(github.head_ref, 'release-please')"
    needs: [beta-info, build]
    runs-on: ubuntu-latest
    steps:
      - name: å¯¼å…¥adapteræ„å»ºäº§ç‰©
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: adapter
          path: .

      - name: è·å–token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: è®¾ç½® bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: latest

      - name: å‘å¸ƒ adapter
        run: |
          bun x pkg-pr-new publish --json output.json --comment=off > adapter.txt 2>&1

          echo "## æˆåŠŸæ¨é€çš„PackageåŒ… :" >> $GITHUB_STEP_SUMMARY
          echo "åŒ…å: \`@puniyu/karin-adapter-puniyu\`" >> $GITHUB_STEP_SUMMARY
          echo "ä½¿ç”¨ pnpm:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "pnpm add https://pkg.pr.new/${{ github.repository }}/@puniyu/karin-adapter-puniyu@${{ needs.beta-info.outputs.short_commit_hash }} -w" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY


          echo "## å®Œæ•´è¾“å‡ºä¿¡æ¯" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat adapter.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: å‘å¸ƒPR è¯„è®º
        if: github.event_name == 'pull_request_target'
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          pr-number: ${{ github.event.pull_request_target.number }}
          github-token: ${{ steps.app-token.outputs.token }}
          comment-tag: execution
          mode: recreate
          message: |
            ğŸ‰ ğŸ‰ ğŸ‰ **æ„å»ºå®Œæˆï¼**
            è¯¥ç‰ˆæœ¬æ˜¯åŸºäº `${{ github.event.pull_request.head.ref || github.ref_name }}` åˆ†æ”¯çš„å¿«ç…§ [**`${{ needs.beta-info.outputs.short_commit_hash }}`**](https://github.com/${{ github.repository }}/commit/${{ needs.beta-info.outputs.short_commit_hash }}) æ‰€æ„å»ºçš„ã€‚

            ä½ å¯ä»¥é€šè¿‡ä»¥ä¸‹å‘½ä»¤å®‰è£…è¯¥ç‰ˆæœ¬ï¼š
            ```
            pnpm add https://pkg.pr.new/${{ github.repository }}/@puniyu/karin-adapter-puniyu@${{ needs.beta-info.outputs.short_commit_hash }} -w
            ```
